GRANT USAGE ON * . * TO 'livinglegend'@'localhost' IDENTIFIED BY 'livinglegend' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;

CREATE DATABASE `world` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `chars` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `logon` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `world` . * TO 'livinglegend'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `chars` . * TO 'livinglegend'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `logon` . * TO 'livinglegend'@'localhost' WITH GRANT OPTION;
